# Generated by Django 5.2.7 on 2026-02-11 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BLOGER', '0004_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
