# Generated by Django 5.2.7 on 2026-02-13 15:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BLOGER', '0006_quiz_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='question3',
            field=ckeditor.fields.RichTextField(max_length=200),
        ),
    ]
