# Generated by Django 5.2.7 on 2026-02-13 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOGER', '0007_alter_quiz_question3'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 2, 13, 15, 44, 26, 435960, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
