# Generated by Django 5.2.7 on 2026-03-17 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BLOGER', '0008_quiz_created_quiz_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='question1',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question2',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question3',
        ),
    ]
