# Generated by Django 5.2.7 on 2026-03-25 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BLOGER', '0010_question_answer_quizresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='qustion',
            new_name='question',
        ),
    ]
