# Generated by Django 5.2.7 on 2026-04-05 14:47

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOGER', '0011_rename_qustion_answer_question'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='score',
            field=models.PositiveIntegerField(choices=[('RT', 'Right'), ('WG', 'Wrong')], max_length=2),
        ),
    ]
