# Generated by Django 5.2.7 on 2026-04-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOGER', '0012_alter_quiz_tags_alter_quizresult_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(choices=[('RT', 'Right'), ('WG', 'Wrong')], max_length=2),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='score',
            field=models.PositiveIntegerField(),
        ),
    ]
