# Generated by Django 5.2.7 on 2026-04-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOGER', '0013_alter_answer_is_correct_alter_quizresult_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.CharField(choices=[('RT', 'Right'), ('WG', 'Wrong')], max_length=2),
        ),
    ]
