# Generated by Django 5.2.7 on 2026-05-08 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BLOGER', '0014_alter_answer_is_correct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created']},
        ),
    ]
